version: "3.8"

services:
    minio-service:
        image: minio/minio
        container_name: minio-container
        command: server /data
        command: server /data --console-address ":9001"
        ports:
            - '9000:9000'
            - '9001:9001'
        volumes:
            - ./data:/data
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        networks:
            - mynetwork
#        healthcheck:
#            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
#            interval: 30s
#            timeout: 20s
#            retries: 3

    mc-service:
        image: minio/mc
        depends_on:
            - minio-service
#            minio-service:
#                condition: service_healthy
        restart: on-failure
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        networks:
            - mynetwork
        entrypoint: >
            /bin/sh -c "
            /usr/bin/mc alias set myminio http://minio-container:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
            /usr/bin/mc mb myminio/bucket;
            /usr/bin/mc mb myminio/bucket-2;
            /usr/bin/mc policy set public myminio/bucket;
            /usr/bin/mc policy set public myminio/bucket-2;
            "

networks:
    mynetwork:
        driver: bridge
